services:
  server:
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=identityserver4
    ports:
      - "5433:5432"
    restart: always